### ISSUE TITLE
A non well formed numeric value encountered

### ISSUE THREAD

**Issue by camohub** [hardevine/LaravelShoppingcart#21]
Hi, I need to make some math with cart total price but if I try to use 
```
$totalPrice = $is_free_shipping
  ? Cart::total) + $activePayment->price - $discount
  : Cart::total() + $activeShippment->price + $activePayment->price - $discount;
```
I am getting an error **A non well formed numeric value encountered.** It is because total() return formated string in form 1,234.56 
Why total() does not return number as I expect? Or why there is not another method like totalFormat() which would return formated string. I thing it is common use case to calculate the final price including other numeric operations.

**Comment by ZayRTun** [comment]
I am having this same issue. Did you manage to find  a solution?

**Comment by ZayRTun** [comment]
Okay so I search on google and found the following solution, use [Sanitize Filters](https://www.php.net/manual/en/filter.filters.sanitize.php)

## Following is what I found that works well so far
```php
(float)filter_var(Cart::subtotal(), FILTER_SANITIZE_NUMBER_FLOAT, FILTER_FLAG_ALLOW_FRACTION)
```

**Comment by camohub** [comment]
I use it this way:
```
   Cart::total(2, '.', '')
```

**Comment by ZayRTun** [comment]
Your right, I totally looked over that. Thanks.
