### ISSUE TITLE
hardevine / LaravelShoppingcart ,, Adding to card not working after destroy

### ISSUE THREAD

**Issue by moustafazare3** [hardevine/LaravelShoppingcart#23]
![image](https://user-images.githubusercontent.com/51272412/101227874-1fbcc980-36a2-11eb-9ab1-aacb00ba24ba.png)
![image](https://user-images.githubusercontent.com/51272412/101227885-25b2aa80-36a2-11eb-9fa4-8cedfd23d96c.png)
![image](https://user-images.githubusercontent.com/51272412/101227892-2b0ff500-36a2-11eb-8c3f-e6caacc0b801.png)

**Comment by phyothiha** [comment]
If your item was successfully added to your cart, there is no way to show **No items in Cart** message. Please check your condition. If no clue, try outputting `dd(Cart::content())` result in index method. By the way, is it Laravel E-Commerce by  Andre Madarang? :D
