### ISSUE TITLE
How to add complex items to cart

### ISSUE THREAD

**Issue by salahxrhl** [hardevine/LaravelShoppingcart#26]
Hello there, I'm facing a trouble, which is adding complex items with dynamic/custom attributes that can change the price.
I'm using this package for an ecommerce app, an online food ordering one to be specific, and an order consists of:
a user has to choose a meal, until here everything works fine, but then, a user has the choice of adding custom additions to his order, for example:
I chose a burger, then I'd like to add more cheese to it for the cost of $1, and a sauce if I wanted to, for another cost of $1. (a total of $2) and I have to display the item with the additions in the cart.
I'm finding myself stuck here; I have tried using nested arrays but I didn't get the result I want.
You guys have any ideas how to implement this?

**Comment by hardevine** [comment]
use Cart::update()

**Comment by salahxrhl** [comment]
UPDATE.
Just in case you came across this, the solution is to separate the optional attributes from the rest of the fields, in my case, I had to separate the sauces and supplements from the rest of the fields,
sauces[]     supplements[]
then I had to check if these two aren't empty in my controller, if it's the case, then json_decode() and then loop through the output array and take the needed fields (in my case, the price and name), push them into an array stored in another variable, then use it as I want.
you can use array_sum() to get the total price if multiple attributes are selected.
GOOD LUCK 😁
