### ISSUE TITLE
any support for laravel 8

### ISSUE THREAD

**Issue by johnef** [hardevine/LaravelShoppingcart#27]
dose the package support laravel 8? @hardevine

**Comment by jordantsap** [comment]
View composer.json file  

"illuminate/support": "5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*|^6|^7|^8",
    	"illuminate/session": "5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*|^6|^7|^8",
       	"illuminate/events": "5.1.*|5.2.*|5.3.*|5.4.*|5.5.*|5.6.*|5.7.*|5.8.*|^6|^7|^8"

**Comment by hardevine** [comment]
it does
