### ISSUE TITLE
Store and Restore returning null

### ISSUE THREAD

**Issue by purusoth8** [hardevine/LaravelShoppingcart#28]
![Screenshot 2021-03-26 190458](https://user-images.githubusercontent.com/40495645/112640378-4c6e3a00-8e67-11eb-960c-18d34422e480.png)

**Comment by hardevine** [comment]
store and restore are for database storage

**Comment by sudjitoe** [comment]
i have the same problem.
I can save properly. but when I restore my cart it returns a null value
Help please..

**Comment by veggigit** [comment]
@sudjitoe after restore u need call to Cart::content

**Comment by tysonchamp** [comment]
Cart::instance('wishlist')->restore($request->user_id);
$data['whishlists'] = Cart::content();
        
return nothing
