### ISSUE TITLE
Is there any functionality to get every ones cart. As its store in session.

### ISSUE THREAD

**Issue by abdulrehmandar2234** [hardevine/LaravelShoppingcart#31]
I want to get every single cart store from different browsers. is it possible.

**Comment by hardevine** [comment]
kindly explain with some example

**Comment by abdulrehmandar2234** [comment]
I need to add a functionality to display favorite products  in my website. the logic for this is to display all the cart and wishlist's content. means display the cart and wishlist of every user for guest on my website. because this pkg don't store cart or wishlist in database. I can't use Cart::all();
do you have any solution. or i have to store every cart and wishlist in db as well when storing it using session(this package).

**Comment by hardevine** [comment]
https://github.com/hardevine/LaravelShoppingcart#database

**Comment by abdulrehmandar2234** [comment]
Thank you I haven't read the full Docs. Another error I'm facing is when I delete cart using this method its give me error The DELETE method is not supported for this route. Supported methods: GET, HEAD, POST. This is the laravel error but may be coming from the package. Do you have any solution. 

 form action="{{route('cart.destroy',$cart->rowId)}}" method="POST"
    @csrf
   @method('DELETE')
    <button type="submit" class="text-gray-32 font-size-26 remove_cart">×</button>
   form
