### ISSUE TITLE
incorrect migration

### ISSUE THREAD

**Issue by WebGenerator** [hardevine/LaravelShoppingcart#38]
SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`identifier` varchar(255) not null, `instance` varchar(255) not null, `content` longtext not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

**Comment by WebGenerator** [comment]
why does not the migration see the config
  Schema::create(config('cart.database.table'), function (Blueprint $table) {
            $table->string('identifier');
            $table->string('instance');
            $table->longText('content');
            $table->nullableTimestamps();

            $table->primary(['identifier', 'instance']);
        });

**Comment by WebGenerator** [comment]
Class 'Gloudemans\Shoppingcart\ShoppingcartServiceProvider' not found 
It's after composer remove. Nice package

**Comment by hardevine** [comment]
kindly check if you can print config variables in tinker / web routes
