### ISSUE TITLE
Softdelete on shopping cart table

### ISSUE THREAD

**Issue by lvidal1** [hardevine/LaravelShoppingcart#40]
Thanks for this package. It is helping me a lot.

My intention is to extend the functionality of the shoppingcart table by keeping the information on the table after checking out the cart.

To achieve that, I need to soft delete the current instance using the identifier. Is it possible to do that? 

I saw `deleteStoredCart `method on the `Cart.php` file but I am not sure how to called as it is protected.

**Comment by hardevine** [comment]
its public
https://github.com/hardevine/LaravelShoppingcart/blob/8dea942f3c61ed450fe7dfee968dc9943fa649f8/src/Cart.php#L414
