### ISSUE TITLE
Specify taxrate in Cart::Add()

### ISSUE THREAD

**Issue by sam-hsbu** [hardevine/LaravelShoppingcart#42]
Hello every one.

I would like to specify a taxrate in Cart::Add() like that : 

```
Cart::add([
            'id' => $product->id, 
            'name' => $product->nom_produit, 
            'qty' => $request->qty, 
            'price' => $prix, 
            'taxrate' => 50
        ])
```
but it doesn't work.

I know we can specify the tax in the "config/cart.php" file but in this case I would like to specify directly in the Cart::Add().

I hope you can understand my request.

Thanks.

Regards.

**Comment by sergomet** [comment]
@sam-hsbu https://github.com/hardevine/LaravelShoppingcart#cartadd

**Comment by sam-hsbu** [comment]
@sergomet that's what I tried of course but it doesn't work : 

_You can optional pass different taxrates to the items._

`Cart::add('293ad', 'Product 1', 1, 9.99, ['size' => 'large'], 20);`

**Comment by Shaka-60hp** [comment]
Yes it doesnt work

**Comment by Shaka-60hp** [comment]
@sam-hsbu I solved it:

on /vendor/hardevine/shoppincart/src/Cart.php  after line 485 I added this line:

`            $cartItem->setTaxRate($id['taxrate']); `

hope it helps

**Comment by nabeelyousafzai** [comment]
i am new in laravel i use shopping cart package how to use this package  i dont understand about the quick usage condition

**Comment by timo75** [comment]
Why has this been closed? It's still not possible to submit the taxrate within an array in Cart:add($array);

**Comment by srcKod** [comment]
this should be fixed by modifying createCartItem method 

on /vendor/hardevine/shoppincart/src/Cart.php line 470, 471
```
  $cartItem = CartItem::fromBuyable($id, $options ?: []); //previous $qty
  $cartItem->setQuantity($qty ?: 1); // previous $name
```
 and the call should be like this to match add method signature in Cart.php 
 
```
  Cart::add($product, null, $qty, null, $options, $taxrate);
```
