### ISSUE TITLE
change item quantity with priced addon

### ISSUE THREAD

**Issue by Malebestia** [hardevine/LaravelShoppingcart#43]
if, in the cart, I change the quantity of an item that has an addon, is the addon's price also considered in the total price calculation?

**Comment by dade1987** [comment]
it is an interesting question. i follow

**Comment by TonySellerHQ** [comment]
if you calculate the price of the item and the addon and add them together then add to the cart the quantity change will include it.

**Comment by hardevine** [comment]
for example ?
