### ISSUE TITLE
Class "Product" not found

### ISSUE THREAD

**Issue by assadali007** [hardevine/LaravelShoppingcart#46]
Hello everyone, i am using the hardevine/shoppingcart this is my controller code this said that

 public function store(Request $request)
    {
      

        Cart::add($request->id,$request->name,1,$request->price)
            ->associate('App\Models\Product');

        return redirect()->route('cart.index')->with('success_message','Item was added to your cart');
    }

this error have come

**Class "Product" not found**

**Comment by assadali007** [comment]
https://flareapp.io/share/J7oajOGm#F54

**Comment by hardevine** [comment]
```php
->associate('App\\Models\\Product');
```

**Comment by assadali007** [comment]
brother still error have come

**Comment by assadali007** [comment]
brother still coming please me to solve out this error https://flareapp.io/share/Rmrn9xKm#F54

**Comment by assadali007** [comment]
it bit confused sometime code working fine and sometime said Class "App\Product" not found
why ??

**Comment by MShahzaib3242** [comment]
I'm continuously getting this error while adding products in bulk
Call to a member function associate() on array
