### ISSUE TITLE
Call to a member function associate() on array

### ISSUE THREAD

**Issue by MShahzaib3242** [hardevine/LaravelShoppingcart#47]
I'm trying to add items on array but I can't associate model with it. I'm getting this error
Call to a member function associate() on array

     $order = Eorder::where('id', $request->id)->first();
      
        $products = array();
        foreach($order->products as $product) {
            
            $products[] = ['id' => $product->id, 'name' => $product->name, 'qty' => $product->pivot->quantity, 'price' => $product->price];
        }
        
        $cartitems = Cart::instance('product')->add($products)->associate('App\Product');

**Comment by hardevine** [comment]
try
```php
$cartitems = Cart::instance('product')->add($products)->associate(App\Product::class);
```

also mention php & laravel versions

**Comment by MShahzaib3242** [comment]
Still same error. The data is in the array.

"php": "^7.3|^8.0",
"laravel/framework": "^8.54",

**Comment by MShahzaib3242** [comment]
![Screenshot 2022-04-27 092144](https://user-images.githubusercontent.com/74776486/165453478-bd1616c7-8664-47a3-94a8-6d1be8419e53.jpg)

Here is the data I'm getting from dd($cartitems);

**Comment by MShahzaib3242** [comment]
Is there anyone who can help me?
